<body>
		<div class="posicao">
			<div class="row" id="login">
				<div class="col segundaColuna">
					<h2>Poste e compartilhe foto com seus seguidores!</h2>
				</div>
				<div class="col">
					<div class="pt-7 formLogin">
						<form method="POST" action="/autenticar">
							<div>
								<input type="email" class="inputInscricao" name="email" placeholder="Email">
							</div>
							<div>
								<input type="password" class="inputInscricao" name="senha" placeholder="Password">
							</div>
							<div class="mt-2 button">
								<button type="submit">Entrar</button>
							</div>
							
						</form>
						<div class="registrar">
							<a class="pt-1" href="/inscreverse">Criar conta</a>
						</div>
					</div>
				</div>
			</div>
		</div>
			

	</body>
</html>