	<body>
		<header>
			<a href="/timeline"><i class="fa-solid fa-camera-retro display-4"></i></a>
			<form method="GET" action="/pesquisar" class="row d-flex flex-nowrap">
				    <div class="col-7">
				    	<input type="text" name="pesquisarPor" class="form-control">
				    </div>
				    <div class="col-4">
				    	<select name="tipoDePesquisa" class="form-select" >
						  <option value="imagens">Imagens</option>
						  <option value="usuarios">Usuários</option>
						</select>
				    </div>
				    <div class="col-1">
				    	<button type="submit" class="btn btn-outline-light rounded-circle p-2"><i class="fa-solid fa-magnifying-glass"></i></button>
				    </div>
			</form>
			<nav>
				<ul class="menu">
					<li><a href="/seu_perfil"><i class="fa-solid fa-user"></i></li>
					<li><a href="/sair">Sair</a></li>
				</ul>
			</nav>
		</header>
		<?php if($this->view->tipoDePesquisa != '' && $this->view->tipoDePesquisa == "usuarios") { ?>
			<?php foreach($this->view->pesquisa as $in_pesq => $pesquisa) { ?>
				<div class="row d-flex justify-content-center pt-2">
					<div class="col-6">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-6">
										<?=$pesquisa['nome']?>
									</div>

									<div class="col-6 d-flex justify-content-end">
										<div>
											<?php if ($pesquisa['curtindo_sn'] == 0) { ?>
												<a href="/acao?acao=curtir&id_usuario=<?=$pesquisa['id']?>&nome=<?=$this->view->pesquisarPor?>" class="btn btn-success">Curtir</a>
											<?php } ?>
											<?php if ($pesquisa['curtindo_sn'] == 1) { ?>
												<a href="/acao?acao=deixar_de_curtir&id_usuario=<?=$pesquisa['id']?>&nome=<?=$this->view->pesquisarPor?>" class="btn btn-danger">Deixar de curtir</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		<?php } ?>

		<div class="flex">
			<?php if($this->view->tipoDePesquisa != '' && $this->view->tipoDePesquisa == "imagens") { ?>
				<?php foreach($this->view->pesquisa as $in_pesq => $pesquisa) { ?>
						<div>
							<img src="<?=$pesquisa['path']?>">
							<p><?=$pesquisa['legenda']?></p>
						</div>
				<?php } ?>
			<?php } ?>
		</div>
	</body>
