<body>

		<header>
			<a href="/timeline"><i class="fa-solid fa-camera-retro display-4"></i></a>
			<form method="GET" action="/pesquisar" class="row d-flex flex-nowrap">
				    <div class="col-7">
				    	<input type="text" name="pesquisarPor" class="form-control">
				    </div>
				    <div class="col-4">
				    	<select name="tipoDePesquisa" class="form-select">
						  <option value="imagens">Imagens</option>
						  <option value="usuarios">Usuários</option>
						</select>
				    </div>
				    <div class="col-1">
				    	<button type="submit" class="btn btn-outline-light rounded-circle p-2"><i class="fa-solid fa-magnifying-glass"></i></button>
				    </div>
			</form>
			<nav>
				<ul class="menu">
					<li><a href=""><i class="fa-solid fa-user"></i></a></li>
					<li><a href="/sair">Sair</a></li>
				</ul>
			</nav>
		</header>

		<section class="flex"><!--Atenção ao nome dessa classe!! -->
			<div class="row">
				<div class="col">	
					<div>
						<form method="POST" action="/postar_imagem" enctype="multipart/form-data">
							<div>
								<input type="file" name="arquivo">
							</div>
							<div>
								<input type="text" name="legenda" required>
							</div>
							<div>
								<button type="submit">Enviar</button>
							</div>
						</form>
					</div>

					<?php foreach($this->view->minhasImagens as $in_img => $imagem) { ?>
						<div class="row pt-4">
							<div class="col d-flex justify-content-center">
								<img src="<?=$imagem['path']?>">
							</div>
							<div class="row">
								<div class="col d-flex justify-content-center">
									<p><?=$imagem['legenda']?></p>
								</div>
							</div>
						</div>
					<?php } ?>
				</div>
			</div>
		</section>

	</body>