<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Miniframework</title>

		<!-- Bootstrap CSS only -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<!--Fontawesome -->
			<script src="https://kit.fontawesome.com/dbd0d73dcf.js" crossorigin="anonymous"></script>
		<!-- Estilo Css -->
		<link rel="stylesheet" type="text/css" href="css/estilo.css">

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>